volumes:
  postgresdata1:

services:
  ingestor:
    restart: unless-stopped
    image: "eosphere/headsup-ingestor:v0.1.9"
    stop_grace_period: 10s
    mem_limit: 1024m
    environment:
      - headsup_serverurl=ws://website/ws
      - headsup_name=Ingestor 1
      - headsup_accesskey=<ENTER ACCESS KEY HERE>
      - headsup_logginglevel=INFO
      - headsup_nodeospollschedule=2.0
      - headsup_votingpollschedule=30.0
      - headsup_bpjsonpollschedule=30.0
      - headsup_hyperionpollschedule=10.0
      - headsup_atomicassetspollschedule=10.0
      # - headsup_sentryurl=""
    logging:
      driver: "journald"
      options:
        tag: "{{.Name}}"
        # max-size: "500m"
    depends_on:
      - website
  website:
    restart: unless-stopped
    image: "eosphere/headsup-website:v0.1.9"
    mem_limit: 300m
    ports:
      - "8000:80"
    environment:
      - LANG=en_AU
      - headsup_server_masterpassword=<ENTER NEW PASSWORD>
      - headsup_server_jwtsecret=<ENTER NEW RANDOM SEED>
      # - headsup_server_sentryurl=
      # - headsup_server_frontendsentryurl=
      - headsup_server_postgreshost=postgres
      - headsup_server_postgrespassword=<POSTGRES PASSWORD>
      #- headsup_server_debugingestorpassword=abc123
      - headsup_server_ingestortimeout=60
      - headsup_logginglevel=INFO
      - headsup_server_rooturl=<https://YOUR ROOT URL>
      - headsup_server_logduration=3
      - headsup_server_failedpingsthreshold=3
      - headsup_server_reminderfrequency=15
      # - headsup_server_emailalerts=true
      # - headsup_server_emailsender=<EMAIL SENDER ADDRESS>
      # - headsup_server_emailto=<ALERTS EMAIL 1>,<ALERTS EMAIL 2>
      # - headsup_server_emailsmtpserver=smtp.gmail.com
      # - headsup_server_emailsmtpssl=false
      # - headsup_server_emailsmtptls=false
      # - headsup_server_emailsmtpport=25
      # - headsup_server_emailsmtpuser=<SMTP SERVER USERNAME>
      # - headsup_server_emailsmtppassword=<SMTP SERVER PASSWORD>
      # - headsup_server_telegramalerts=true                                                                                                                                                                                            
      # - headsup_server_telegrambot=xxxxxxxxxx:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                                                                                                                                     
      # - headsup_server_telegramchat=-zzzzzzzzzz
      # - headsup_server_slackalerts=true
      # - headsup_server_slackhook=https://hooks.slack.com/services/xxxx/yyyy/zzzz
    logging:
      driver: "journald"
      options:
        tag: "{{.Name}}"
        #max-size: "500m"
    depends_on:
      - postgres
  postgres:
    restart: unless-stopped
    image: "postgres:13.7"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=<POSTGRES PASSWORD>
    volumes:
      - postgresdata1:/var/lib/postgresql
